### ISSUE TITLE
Can I use this gem in Heroku?

### ISSUE THREAD

**Issue by zulhfreelancer** [mikeatlas/realtime-rails#9]
Hi,

I'm a Heroku user. Can I use this gem in Heroku?

Can someone please share tutorial or highlight important steps to do?

Thanks.

**Comment by mikeatlas** [comment]
Yes, most definitely you can, the demo using redis is on the free tier of Heroku. 

There are many guides on Heroku's site itself for hosting Rails applications on the free tier, several free tier redis plans, and plenty of hosting Node.js application hosting guides. I'm sorry but you should be able to find the information yourself just fine without me putting together a tutorial - the [documentation](http://mikeatlas.github.io/realtime-rails/) I wrote for the gem is more than enough combined with other guides published on Heroku.
